# Site settings
title: electroflame's place
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://electroflame.github.io"
twitter_username: electroflame_X
github_username:  electroflame
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
