# Site settings
title: electroflame's place
email: your-email@yourdomain.com
description: "The place where all of my stuff goes."
baseurl: "http://electroflame.github.io"
url: "http://electroflame.github.io"
twitter_username: electroflame_
github_username:  electroflame
steam_username:  electroflame

owner:  electroflame
owner_about_url_slug:  /about
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
